### PR TITLE
fix: rename ngc api key;issue #82

### PR DESCRIPTION
**Pull request by sujituk**
The variable name "NGC_CLI_API_KEY" needs to be updated to "NGC_API_KEY". Issue here: https://github.com/NVIDIA/nim-deploy/issues/82

https://github.com/NVIDIA/nim-deploy/blob/main/cloud-service-providers/google-cloud/gke/infra/3-config/main.tf
line 89:
NGC_CLI_API_KEY => NGC_API_KEY

### CODE REVIEW

**Review by JamesMaki — APPROVED** [review]

**Comment by JamesMaki** [comment]
Can you sign this commit with your GPG key?

**Comment by JamesMaki** [comment]
@sujituk

**Comment by sujituk** [comment]
@JamesMaki singed using new commit.

**Comment by JamesMaki** [comment]
The main branch requires all commits to be signed, can you sign the previous one as well?

**Comment by sujituk** [comment]
@JamesMaki I've another incoming PR for GCS Caching. Okay to include these changes in that PR and close this?

**Comment by JamesMaki** [comment]
Sure, that works. Thank you!

**Comment by sujituk** [comment]
Included in https://github.com/NVIDIA/nim-deploy/pull/90

**Pull request closed without merging**
